name: Black Code Formatter
on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
          args: >
            SABnzbd.py
            sabnzbd
            scripts
            tools
            tests
            --line-length=120
            --target-version=py36
            --check
