name: Black Code Formatter
on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!master'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
          args: >
            scripts
            tools
            tests
            sabnzbd/utils
            sabnzbd/__init__.py
            sabnzbd/cfg.py
            sabnzbd/config.py
            sabnzbd/emailer.py
            sabnzbd/constants.py
            sabnzbd/decorators.py
            sabnzbd/decoder.py
            sabnzbd/database.py
            sabnzbd/getipaddress.py
            sabnzbd/filesystem.py
            sabnzbd/dirscanner.py
            sabnzbd/postproc.py
            sabnzbd/misc.py
            sabnzbd/lang.py
            sabnzbd/nzbparser.py
            sabnzbd/notifier.py
            sabnzbd/rss.py
            sabnzbd/par2file.py
            sabnzbd/version.py
            --line-length=120
            --target-version=py35
            --check
